### ISSUE TITLE
Argument : ✔️Issue : 주문 테이블에서 매출 테이블로 정보를 복사하는 시기 문제

### ISSUE THREAD

**Issue by RTUnu12** [UFO-System/ufo-front#7]
## 논의 주제
매출 갱신 시기에 따라 프론트앤드에서 매출 갱신 버튼을 추가할 것인가?

## 배경
현재 프론트엔드에서 보내준 자료들을 바탕으로 DB를 제작하고 있으며, 이때 매출 테이블에 주문 테이블의 정보들을 복사하는 프로시저를 정의하는 과정에서 논의점이 생기게 되었습니다.

## 논의하고자 하는 내용
현재 매출을 언제 등록할 건가에 대해 두 가지 방법이 있습니다.

* 하루가 지나 주문 테이블이 초기화가 될 때
: 성능 상 효율적이나 초기화되지 않는 시간에는 현재까지의 매출을 확인할 수 없음
-> 프론트의 매출 탭에서 "매출 강제 갱신"을 통해 갱신 가능 (이 이슈가 프론트에 있는 이유)

* 주문이 수락되는 즉시 매출 테이블에 복사
: 어느 시기나 최신으로 갱신된 매출 정보를 볼 수 있으나 성능 상 비효율적

## 제안된 아이디어
기본적으로 하루가 지날 때 주문의 정보가 매출로 복사, 이후 주문 테이블의 클리어
이때 위 시기가 아니더라도 최신의 매출 정보를 볼 수 있게 프론트앤드 측에서 해당 프로시저를 실행하는 버튼을 구현하는 것입니다.

## 추가 정보
![image](https://github.com/UFO-System/ufo-front/assets/73762862/cedc1638-6d8d-4dd1-ac11-02e79404e817)
![image](https://github.com/UFO-System/ufo-front/assets/73762862/0e1e5fbe-3b3b-48e9-8d84-0b97680f4ac1)

## 결론 도출을 위한 질문
1. 더 좋은 방법이 있습니까?
2. 지금 프론트앤드 측에서 버튼을 추가할 수 있습니까?

**Comment by genwo123** [comment]
축제에서 사용되는 방향이라 매출이 궁금한 경우가 많을것 같습니다. 하루를 넘기는 방식은 조금 더 짧게 1시간이나 3시간 단위면 더 좋을것 같고, 기본적으로 새로고침 해서 바로 끌어오는 버튼이 있으면 좋을것 같습니다.

축제 주점은 주로 오전에 활동하는 주점과 밤에 하는 주점이 있는데 하루 단위보다는 시간제로 끊는게 좋다고 생각합니다. 이 방식으로 진행은 어려울까요?

**Comment by RTUnu12** [comment]
가능합니다. 그러면 1시간 단위로 자동으로 갱신하면서 바로 끌어올 수도 있는 프로시저를 제작하면 될 거 같습니다.

**Comment by BAEzunz** [comment]
Front-end 측에서 답변드립니다. 해당 프로시저를 실행하는 버튼 구현 가능합니다.
